<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa [
    <!ELEMENT empresa (equipo+)>
    <!ELEMENT equipo ((empleado+,oficina)|director+)>
    <!ELEMENT empleado (#PCDATA)>
    <!ELEMENT oficina EMPTY>
    <!ELEMENT director (#PCDATA)>
    <!ATTLIST equipo nombre ID #REQUIRED>
    <!ATTLIST oficina direccion CDATA "Sede central">
    <!ATTLIST empleado  dni ID #REQUIRED
                        jornada (completa|reducida) "completa"
                        fotografia ENTITY #IMPLIED>
    <!ATTLIST director  dni ID #IMPLIED
                        subordinados IDREFS #IMPLIED>
    <!ENTITY juan_ortiz SYSTEM "JOrtiz.jpg" NDATA jpg>
    <!ENTITY luisa_gomez SYSTEM "LGomez.jpg" NDATA jpg>
    <!NOTATION jpg SYSTEM "image/jpg">
]>
<empresa>
    <equipo nombre="A">
        <empleado dni="N1111" fotografia="juan_ortiz">Juan Ortiz</empleado>
        <empleado dni="N2222">Julián Pérez</empleado>
        <oficina />
    </equipo>
    <equipo nombre="B">
        <empleado dni="N3333" fotografia="luisa_gomez">Luisa Gómez</empleado>
        <empleado dni="N4444" jornada="reducida">Andrés Romero</empleado>
        <oficina direccion="Avenina de la Industria s/n" />
    </equipo>
    <equipo nombre="D">
        <director subordinados="A B">Alejandra Martín</director>
    </equipo>
</empresa>