=== BertoMP/TemarioDAW/LLMM/EJERCICIOS/02 EJERCICIOS/UD3/E07.XSD2/vuelos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hojaDeVuelos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vuelo" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="origen" type="ciudad" />
                            <xs:element name="destino" type="ciudad" />
                            <xs:element name="hora">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="salida" type="xs:time" />
                                        <xs:element name="llegada" type="xs:time" />
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" />
                        <xs:attribute name="admitePasajeros" type="xs:boolean" />
                        <xs:attribute name="aerolÃ­nea" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="fechaDelDia" type="xs:date" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="ciudad">
        <xs:restriction base="xs:string">
            <xs:length value="3" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== BertoMP/TemarioDAW/LLMM/EJERCICIOS/02 EJERCICIOS/UD3/E07.XSD2/vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<hojaDeVuelos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="vuelos.xsd" 
    fechaDelDia="2022-01-01">
    <vuelo id="IB8860" admitePasajeros="true" aerolínea="Iberia">
        <origen>MAD</origen>
        <destino>ALC</destino>
        <hora>
            <llegada>10:54:00</llegada>
        </hora>
    </vuelo>
    <vuelo id="TP1027" admitePasajeros="false" aerolínea="TAP Air Portugal">
        <origen>MAD</origen>
        <destino>LIS</destino>
        <hora>
            <salida>12:05:00</salida>
        </hora>
    </vuelo>
</hojaDeVuelos>
